- src/test/resources/features/DepartureFE/E2E/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-XI.feature
- src/test/resources/features/DepartureFE/sections/RouteDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/GuaranteeDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/AddAnotherTransitRouteCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/BindingItineraryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/OfficeOfDestinationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/TransitRouteAddCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/TransitRouteCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TaskListPage.scala
Route details function test and E2E test
> Route details function test and E2E test

- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/TransitRouteAddAnotherCountryPage.scala
Change the name of page to AddAnotherTransitRouteCountryPage
> Change the name of page to AddAnotherTransitRouteCountryPage

- src/test/resources/features/DepartureFE/sections/RouteDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Transit/OfficeOfTransitEtaPage.scala
- fixing the change of the ETA page ids
> dateTimeId: Fix for the merged PR braking the pipeline

- src/test/resources/features/DepartureFE/E2E/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-XI.feature
- src/test/resources/features/DepartureFE/sections/RouteDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteExitStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteTransitStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Exit/AddAnotherOfficeOfExitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Exit/OfficeOfExitCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Exit/OfficeOfExitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Transit/OfficeOfTransitEtaPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Transit/OfficeOfTransitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/Transit/T2DeclarationPage.scala
Test for 884 journey test and fix test
> Test for 884 journey test and fix test

- src/test/resources/features/DepartureFE/E2E/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-XI.feature
- src/test/resources/features/DepartureFE/Sections/TransportDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Transport/TransportDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/ContainerDetails/ContainersPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/ApplyUcrToAllItemsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/ContainersPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/CountryOfDispatchPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/ItemsDestinationCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/ItemsSameDestinationCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Transport/TransportDetails/UniqueConsignmentReferencePage.scala
> added the transport details testcases

- src/test/resources/features/DepartureFE/E2E/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-XI.feature
- src/test/resources/features/DepartureFE/Sections/RouteDetails.feature
- src/test/resources/features/DepartureFE/Sections/TraderDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteDetailsLocationOfGoodsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/TraderDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/AddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Arrival/LocationOfGoodsType/LocationOfGoodsAddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/LocationOfGoods/LocationOfGoodsAddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/RouteDetails/LocationOfGoods/LocationOfGoodsCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/Consignee/ConsigneeAddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/Consignee/ConsigneeCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/Consignor/ConsignorAddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/Consignor/ConsignorCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/TransitHolder/HolderAddressPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/TraderDetails/TransitHolder/HolderCountryPage.scala
added the trader details ( Pincode, Country validation )testcases
> added the trader details ( Pincode, Country validation )testcases

- src/test/resources/features/ArrivalFE/E2E/End-to-end.feature
- src/test/resources/features/ArrivalFE/Section/Arrival.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/E2E/End-to-end-XI.feature
- src/test/resources/features/DepartureFE/Sections/RouteDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Arrivals/IdentificationStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteDetailsLocationOfGoodsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/RouteDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/AddressCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Arrival/Identification/ConsigneeEoriTinPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Arrival/Identification/OfficeOfDestinationPage.scala
CTCP-1352 new update arrival and E2E test by added office of destination page, EORI number or TIN page and removed CYA page
> CTCP-1352 new update arrival and E2E test by added office of destination page

- src/test/resources/features/DepartureFE/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/End-to-end-XI.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Departures/Transport/TransportDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/TransportDetails/ItemsSameDispatchCountryPage.scala
> Add test for items being dispatched from the same country in the transportation section

- src/test/resources/features/DepartureFE/DepartureFinal/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/DepartureFinal/End-to-end-XI.feature
- change went in but the E2E final journeys haven't been updated
> CTCP-3408: Change to carriers EORI-TIN h1

- src/test/resources/features/DepartureFE/DepartureFinal/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/DepartureFinal/GuaranteeDetails.feature
- src/test/resources/features/DepartureFE/DepartureTransition/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/DepartureTransition/GuaranteeDetails.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Departures/Guarantee/GuaranteeDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Departures/Transport/CarrierDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Guarantee/GuaranteeDefaultLiabilityPage.scala
- updated both transition and post-transition as both are affected
> CTCP-3443: Adding default liability amount to guarantee details

- src/test/resources/features/ArrivalFE/Final Arrivals/Arrival.feature
- src/test/resources/features/ArrivalFE/Transition/Arrival.feature
- src/test/resources/features/ArrivalFE/Transition/End-to-end.feature
- src/test/scala/uk/gov/hmrc/test/ui/pages/Arrivals/LocationOfGoodsType/LocationOfGoodsIdentificationPage.scala
- Adjusting the logic to fit in the matrix as per the ticket
- Modified selector for location of goods to use value
> CTCP-3467: Adding location of goods matrix logic

- src/test/resources/features/DepartureFE/DepartureTransition/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/DepartureTransition/ItemDetails.feature
- adding journey in Transition to cover the package of 0 being accepted
> CTCP-3587: Packages of 0 accepted in Transition and not in Post Transition

- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForAll.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForPresentationNotification.scala
> CTCP-3866-2

- src/test/resources/features/PresentationNotificationFE/PresentationNotificationFE.feature
- src/test/resources/xml/IE015PrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE015PrelodgedDepartureDeclarationWithLocationOfGoods.xml
- src/test/resources/xml/IE015SimplifiedPrelodgedDepartureDeclaration.xml
Test to fix failing test - updated CustomsOfficeOfDestinationDeclared
> CTCP-3889 - Test Update

- src/test/resources/features/PresentationNotificationFE/IE13PresentationNotificationFE.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationFE.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/PresentationNotification/PresentationNotificationStepDef.scala
Update to common step defs to make them more unique
> common-step-def-fix

- src/test/resources/features/PresentationNotificationFE/IE13PresentationNotificationFE.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationFE.feature
- src/test/resources/xml/IE004AmendmentAcceptance.xml
- src/test/resources/xml/IE007ArrivalNotification.xml
- src/test/resources/xml/IE013DeclarationAmendment.xml
- src/test/resources/xml/IE013PrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE013PrelodgedDepartureDeclarationWithLocationOfGoods.xml
- src/test/resources/xml/IE013SimplifiedPrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE013SimplifiedPrelodgedDepartureDeclarationFull.xml
- src/test/resources/xml/IE014DeclarationCancellation.xml
- src/test/resources/xml/IE015DepartureDeclaration.xml
- src/test/resources/xml/IE015PrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE015PrelodgedDepartureDeclarationWithLocationOfGoods.xml
- src/test/resources/xml/IE015SimplifiedPrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE015SimplifiedPrelodgedDepartureDeclarationFull.xml
- src/test/resources/xml/IE028MRNAllocated.xml
- src/test/resources/xml/IE043UnloadingPermissionWithSeals.xml
- src/test/resources/xml/IE044UnloadingRemarksNotificationWithSeals.xml
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForAllTransition.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForPresentationNotification.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/PresentationNotification/PresentationNotificationStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/ActiveMeansOfBorderTransport/ActiveMeansOfBorderTransportIdentificationPage.scala
- Refactor XMLs with valid data
> Refactoring of presentation notification

- src/test/resources/features/DepartureFE/DepartureFinal/TransportDetails.feature
- src/test/resources/features/DepartureFE/DepartureTransition/End-to-end-GB.feature
- src/test/resources/features/DepartureFE/DepartureTransition/TransportDetails.feature
No change required for the post transition E2E tests
> Updated Transport section of tests for new change/remove logic

- src/test/resources/features/DepartureFE/DepartureFinal/TransportDetails.feature
- src/test/resources/features/DepartureFE/DepartureTransition/TransportDetails.feature
To cover the inland mode optionality for transition vs final
> C521-inlandmode-bug: Adding additional scenaraio in transport details

- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationCYA.feature
- src/test/resources/xml/IE015NormalPrelodgedDepartureDeclarationComplete.xml
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/PresentationNotification/PresentationNotificationStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/CYAPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/DepartureMenasOfTransport/DepartureMeansOfTransportIdentificationNumberPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/DepartureMenasOfTransport/DepartureMeansOfTransportTransportCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/DepartureMenasOfTransport/DepartureMeansOfTransportWhichIdentificationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/Represntative/ActingAsRepresentative.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/Represntative/AddContactDetailsRepresentativePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/Represntative/AddContactNameRepresentativePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/Represntative/AddContactPhoneNumberRepresentativePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/Represntative/AddEORINumberOrTraderIdentificationNumber.scala
Created scripst for Rep, inland mode and Departure means of trasport
> added tests for rep and inlandmode and departure mode of transport

- src/test/resources/features/ArrivalFE/ArrivalTransition/End-to-end.feature
There's no value in the check mode steps
> CTCP-4841: Remove unnecessary check mode steps

- src/test/resources/features/ManageFE/ManageTransitMovementsDepartures.feature
- src/test/resources/features/PresentationNotificationFE/IE13PresentationNotificationFE.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationCYA.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationFE.feature
- src/test/resources/xml/IE015NormalPrelodgedDepartureDeclarationComplete.xml
- src/test/resources/xml/IE015PrelodgedDepartureDeclaration.xml
- src/test/resources/xml/IE015PrelodgedDepartureDeclarationWithLocationOfGoods.xml
- src/test/resources/xml/IE015SimplifiedPrelodgedDepartureDeclarationComplete.xml
- src/test/resources/xml/IE015SimplifiedPrelodgedDepartureDeclarationFull.xml
- src/test/resources/xml/IE060ControlDecisionType2.xml
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Manage/DepartureDeclarationsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Manage/ManageStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/PresentationNotification/PresentationNotificationStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Manage/ManageDepartures/PreLodgedGoodsUnderControlPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/ConfirmationNeededPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/MoreInformationPage.scala
- Chances to the pre-lodge language in H1s and links
- Added an intention to control type 2 case
- Added some changes to the XML
> CTCP-4906:Change to language plus intention to control case

- src/test/resources/features/UnloadingFE/UnloadingCrossCheck.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForAll.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForAllTransition.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Unloading/UnloadingStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ChangeCUSCodePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ChangeCommodityCodePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ChangeGrossWeightPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ChangeNetWeightPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ChangeNomenclatureCodePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/CrossCheckHouseConsignmentPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/RemoveCommodityCodePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/RemoveGrossWeightsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/RemoveNetWeightsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/RemoveNomenclatureCodePage.scala
Updates to merge work together for CTCP-4612
> CTCP-4612-2

- src/test/resources/features/UnloadingFE/UnloadingCrossAddRemoveMode.feature
- src/test/resources/features/UnloadingFE/UnloadingCrossCheckChangeMode.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Departures/Items/ItemDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Unloading/UnloadingStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/AddNewConsignmentAdditionalReferenceNumberPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/ConsignmentCrossCheckPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/HouseConsignmentPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewItemLevelAdditionalReferenceNumberPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewItemLevelAdditionalReferenceTypePage.scala
- Added Additional reference change mode at item level
- Added Additional reference add and more at consignment level
- Small refactor
> CTCP-4678: Added Item level Additional reference Change mode + Refactor

- src/test/resources/features/ArrivalFE/ArrivalFinal/AmendNotification.feature
- src/test/resources/features/ArrivalFE/ArrivalTransition/AmendNotification.feature
- src/test/resources/features/CancellationFE/Cancellation.feature
- src/test/resources/features/DepartureFE/DepartureFinal/AmendDeclaration.feature
- src/test/resources/features/DepartureFE/DepartureTransition/AmendDeclaration.feature
- src/test/resources/features/ManageFE/ManageTransitMovementsArrivals.feature
- src/test/resources/features/ManageFE/ManageTransitMovementsDepartures.feature
- src/test/resources/features/PresentationNotificationFE/IE13PresentationNotificationFE.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationCYA.feature
- src/test/resources/features/PresentationNotificationFE/IE15PresentationNotificationFE.feature
- src/test/resources/features/UnloadingFE/Unloading.feature
- src/test/resources/features/UnloadingFE/UnloadingCrossAddRemoveMode.feature
- src/test/resources/features/UnloadingFE/UnloadingCrossCheckChangeMode.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Manage/ArrivalNotificationsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Unloading/UnloadingStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/CYAPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Manage/ManageTransitMovementsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/HouseConsignmentRemoveHCPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/utils/Message.scala
- update transition View departure declaration and View arrival notification links
- update post-transition View departure declaration and View arrival notification links
- Added ToDos for 1 July to revert the links
> CTCP-5265: Cutover links update

- src/test/resources/features/DepartureFE/DepartureTransition/End-to-end-GB.feature
When container indicator = 0 but transport equipment is present
> CTCP-5462: Adding mandatory seal to transport equipment

- src/test/resources/features/GuaranteeBalanceFE/GetGuaranteeBalance.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/GuaranteeBalance/GetGuaranteeBalanceStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceAvailableBalanceConfirmationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceCYAPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceCantCheckBalancePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceDetailsDoNotMatchPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceGuaranteeAccessCodePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceGuaranteeRefNumberPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GetBalanceInvalidGuaranteePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GuaranteeBalancePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/GetGuaranteeBalance/GuaranteeRefNumberPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Manage/ManageTransitMovementsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/TransportEquipment/RemoveSealFromTransportEquipmentPage.scala
- feature 1 : A concise way of presenting two journeys by accommodating the change links: The Guarantee Reference Number (GRN) and access code do not match page and Available balance journey
- feature 2 : Invalid guarantee
> CTCP-5341: Added get guarantee balance feature and steps

- src/test/resources/features/UnloadingFE/Unloading.feature
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Unloading/UnloadingStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/CYAPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CheckGoodsAndNoteDiscrepanciesPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/DownloadUnloadingPermissionsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/EnterAllSealsIdentificationNumbersPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/EnterOriginalSealsIdentificationCommentPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/GoodsTooLargeToFitIntoContainerPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/HaveSealsBeenReplacedByCustomsPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/IsRevisedUnloadingProcedurePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/UnloadAndNoteDiscrepanciesPage.scala
For  unloading with new agreement
> CTCP-5513: Added the routes to the new CYA page

- README.md
- src/test/scala/uk/gov/hmrc/test/ui/cucumber/runner/RunnerForGetGuaranteeBalance.scala
- Added Get Guarantee balance runner
- updated README
> CTCP-5341-1: Added Guarantee balance runner

- src/test/resources/features/ManageFE/ManageTransitMovementsArrivals.feature
- src/test/resources/features/UnloadingFE/Unloading.feature
- added an IE057 scenario in Unloading feature
- removed unnecessary steps from Manage FE feature
> CTCP-6158: Update to unloading journey in Manage FE feature

- src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/Departures/Items/ItemDetailsStepDef.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Guarantee/GuaranteeLiabilityCurrencyPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/ActiveMeansOfBorderTransport/ActiveBorderMeansOfTransportOfficeOfTransitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/ActiveMeansOfBorderTransport/ActiveMeansOfBorderTransportCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/DepartureMenasOfTransport/DepartureMeansOfTransportTransportCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/LocationOfGoodsCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/PlaceOfLoadingCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/PresentationNotification/TransportEquipmentPage.scala
Change id for labelBy for pre-lodged and guarantee details as per tickets
CTCP-6360 
CTCP-6366
> CTCP-6360: Change Id for labelBy includes CTCP-6366

- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Documents/Documents/DocumentPreviousTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Documents/Documents/DocumentTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Documents/Previous/PackageTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Items/AdditionalInformationTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Items/AdditionalReferenceTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Items/PackageTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Exit/OfficeOfExitCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Exit/OfficeOfExitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/LocationOfGoods/LocationOfGoodsCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/LocationOfGoods/LocationOfGoodsCustomsOfficeIdentificationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/PlaceOfLoading/PlaceOfLoadingCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/PlaceOfUnloading/PlaceOfUnloadingCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Routing/CountryOfDestinationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Routing/OfficeOfDestinationPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Routing/TransitRouteCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Transit/OfficeOfTransitCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/RouteDetails/Transit/OfficeOfTransitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/BorderMeansOfTransport/BorderMeansOfTransportCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/BorderMeansOfTransport/BorderMeansOfTransportOfficeOfTransitPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/InlandModeOfTransport/TransportCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/TransportDetails/CountryOfDispatchPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Departures/Transport/TransportDetails/ItemsDestinationCountryPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/AddDocumentTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/CountryForNewDepartureMeansOfTransportPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/DepartureMeansOfTransport/CountryTypeVehicleRegisteredPage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewAdditionalReferenceTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewDocumentTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewItemLevelAdditionalReferenceTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/NewItemLevelPackageTypePage.scala
- src/test/scala/uk/gov/hmrc/test/ui/pages/Unloading/CrossCheckPagePages/TransportEquipment/ItemTypeForTransportEquipmentPage.scala
- Transport section - CTCP-6363
- Route section - CTCP-6362
- Unloading FE - CTCP-6359
- Document section - CTCP-6364
> CTCP-6363: Updated ids for labelledBy 
